package com.bj.entity;

import java.io.Serializable;

public class SysRegion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_id
     *
     * @mbggenerated
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_name
     *
     * @mbggenerated
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_short_name
     *
     * @mbggenerated
     */
    private String regionShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_code
     *
     * @mbggenerated
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_parent_id
     *
     * @mbggenerated
     */
    private String regionParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_region.region_level
     *
     * @mbggenerated
     */
    private Integer regionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_id
     *
     * @return the value of sys_region.region_id
     *
     * @mbggenerated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_id
     *
     * @param regionId the value for sys_region.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_name
     *
     * @return the value of sys_region.region_name
     *
     * @mbggenerated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_name
     *
     * @param regionName the value for sys_region.region_name
     *
     * @mbggenerated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_short_name
     *
     * @return the value of sys_region.region_short_name
     *
     * @mbggenerated
     */
    public String getRegionShortName() {
        return regionShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_short_name
     *
     * @param regionShortName the value for sys_region.region_short_name
     *
     * @mbggenerated
     */
    public void setRegionShortName(String regionShortName) {
        this.regionShortName = regionShortName == null ? null : regionShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_code
     *
     * @return the value of sys_region.region_code
     *
     * @mbggenerated
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_code
     *
     * @param regionCode the value for sys_region.region_code
     *
     * @mbggenerated
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_parent_id
     *
     * @return the value of sys_region.region_parent_id
     *
     * @mbggenerated
     */
    public String getRegionParentId() {
        return regionParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_parent_id
     *
     * @param regionParentId the value for sys_region.region_parent_id
     *
     * @mbggenerated
     */
    public void setRegionParentId(String regionParentId) {
        this.regionParentId = regionParentId == null ? null : regionParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_region.region_level
     *
     * @return the value of sys_region.region_level
     *
     * @mbggenerated
     */
    public Integer getRegionLevel() {
        return regionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_region.region_level
     *
     * @param regionLevel the value for sys_region.region_level
     *
     * @mbggenerated
     */
    public void setRegionLevel(Integer regionLevel) {
        this.regionLevel = regionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", regionId=").append(regionId);
        sb.append(", regionName=").append(regionName);
        sb.append(", regionShortName=").append(regionShortName);
        sb.append(", regionCode=").append(regionCode);
        sb.append(", regionParentId=").append(regionParentId);
        sb.append(", regionLevel=").append(regionLevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}