package com.bj.entity;

import java.io.Serializable;

public class Test02 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test02.zone_id
     *
     * @mbggenerated
     */
    private String zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test02.zone_name
     *
     * @mbggenerated
     */
    private String zoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test02.zone_short_name
     *
     * @mbggenerated
     */
    private String zoneShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test02.zone_code
     *
     * @mbggenerated
     */
    private String zoneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test02.zone_parent_id
     *
     * @mbggenerated
     */
    private String zoneParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test02.zone_level
     *
     * @mbggenerated
     */
    private Integer zoneLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test02
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test02.zone_id
     *
     * @return the value of test02.zone_id
     *
     * @mbggenerated
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test02.zone_id
     *
     * @param zoneId the value for test02.zone_id
     *
     * @mbggenerated
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId == null ? null : zoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test02.zone_name
     *
     * @return the value of test02.zone_name
     *
     * @mbggenerated
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test02.zone_name
     *
     * @param zoneName the value for test02.zone_name
     *
     * @mbggenerated
     */
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName == null ? null : zoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test02.zone_short_name
     *
     * @return the value of test02.zone_short_name
     *
     * @mbggenerated
     */
    public String getZoneShortName() {
        return zoneShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test02.zone_short_name
     *
     * @param zoneShortName the value for test02.zone_short_name
     *
     * @mbggenerated
     */
    public void setZoneShortName(String zoneShortName) {
        this.zoneShortName = zoneShortName == null ? null : zoneShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test02.zone_code
     *
     * @return the value of test02.zone_code
     *
     * @mbggenerated
     */
    public String getZoneCode() {
        return zoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test02.zone_code
     *
     * @param zoneCode the value for test02.zone_code
     *
     * @mbggenerated
     */
    public void setZoneCode(String zoneCode) {
        this.zoneCode = zoneCode == null ? null : zoneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test02.zone_parent_id
     *
     * @return the value of test02.zone_parent_id
     *
     * @mbggenerated
     */
    public String getZoneParentId() {
        return zoneParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test02.zone_parent_id
     *
     * @param zoneParentId the value for test02.zone_parent_id
     *
     * @mbggenerated
     */
    public void setZoneParentId(String zoneParentId) {
        this.zoneParentId = zoneParentId == null ? null : zoneParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test02.zone_level
     *
     * @return the value of test02.zone_level
     *
     * @mbggenerated
     */
    public Integer getZoneLevel() {
        return zoneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test02.zone_level
     *
     * @param zoneLevel the value for test02.zone_level
     *
     * @mbggenerated
     */
    public void setZoneLevel(Integer zoneLevel) {
        this.zoneLevel = zoneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test02
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zoneId=").append(zoneId);
        sb.append(", zoneName=").append(zoneName);
        sb.append(", zoneShortName=").append(zoneShortName);
        sb.append(", zoneCode=").append(zoneCode);
        sb.append(", zoneParentId=").append(zoneParentId);
        sb.append(", zoneLevel=").append(zoneLevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}