package com.bj.entity;

import java.io.Serializable;
import java.util.Date;

public class Test01 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.int_unsigned
     *
     * @mbggenerated
     */
    private Integer intUnsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.int_type
     *
     * @mbggenerated
     */
    private Integer intType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.bigint_unsigned20
     *
     * @mbggenerated
     */
    private Long bigintUnsigned20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.bigint_unsigned255
     *
     * @mbggenerated
     */
    private Long bigintUnsigned255;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.big_int
     *
     * @mbggenerated
     */
    private Long bigInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.big_int_255
     *
     * @mbggenerated
     */
    private Long bigInt255;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.varchar
     *
     * @mbggenerated
     */
    private String varchar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.bit
     *
     * @mbggenerated
     */
    private Boolean bit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.bit_64
     *
     * @mbggenerated
     */
    private Boolean bit64;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.tiny_int
     *
     * @mbggenerated
     */
    private Byte tinyInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.tiny_int_unsigned
     *
     * @mbggenerated
     */
    private Byte tinyIntUnsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.small_int
     *
     * @mbggenerated
     */
    private Short smallInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.small_int_unsigned
     *
     * @mbggenerated
     */
    private Short smallIntUnsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.char_utf8
     *
     * @mbggenerated
     */
    private String charUtf8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.char_utf8gbk
     *
     * @mbggenerated
     */
    private String charUtf8gbk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.datetime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.float_type
     *
     * @mbggenerated
     */
    private Float floatType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.float_unsigned
     *
     * @mbggenerated
     */
    private Float floatUnsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.decimal
     *
     * @mbggenerated
     */
    private Long decimal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.numeric
     *
     * @mbggenerated
     */
    private Long numeric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.double_type
     *
     * @mbggenerated
     */
    private Double doubleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.double_unsigned
     *
     * @mbggenerated
     */
    private Double doubleUnsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.integer_type
     *
     * @mbggenerated
     */
    private Integer integerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.integer_unsigned
     *
     * @mbggenerated
     */
    private Integer integerUnsigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.tinytext
     *
     * @mbggenerated
     */
    private String tinytext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.year
     *
     * @mbggenerated
     */
    private Date year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.enum_type
     *
     * @mbggenerated
     */
    private String enumType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.binary
     *
     * @mbggenerated
     */
    private byte[] binary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.blob
     *
     * @mbggenerated
     */
    private byte[] blob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test01.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test01
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.int_unsigned
     *
     * @return the value of test01.int_unsigned
     *
     * @mbggenerated
     */
    public Integer getIntUnsigned() {
        return intUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.int_unsigned
     *
     * @param intUnsigned the value for test01.int_unsigned
     *
     * @mbggenerated
     */
    public void setIntUnsigned(Integer intUnsigned) {
        this.intUnsigned = intUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.int_type
     *
     * @return the value of test01.int_type
     *
     * @mbggenerated
     */
    public Integer getIntType() {
        return intType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.int_type
     *
     * @param intType the value for test01.int_type
     *
     * @mbggenerated
     */
    public void setIntType(Integer intType) {
        this.intType = intType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.bigint_unsigned20
     *
     * @return the value of test01.bigint_unsigned20
     *
     * @mbggenerated
     */
    public Long getBigintUnsigned20() {
        return bigintUnsigned20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.bigint_unsigned20
     *
     * @param bigintUnsigned20 the value for test01.bigint_unsigned20
     *
     * @mbggenerated
     */
    public void setBigintUnsigned20(Long bigintUnsigned20) {
        this.bigintUnsigned20 = bigintUnsigned20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.bigint_unsigned255
     *
     * @return the value of test01.bigint_unsigned255
     *
     * @mbggenerated
     */
    public Long getBigintUnsigned255() {
        return bigintUnsigned255;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.bigint_unsigned255
     *
     * @param bigintUnsigned255 the value for test01.bigint_unsigned255
     *
     * @mbggenerated
     */
    public void setBigintUnsigned255(Long bigintUnsigned255) {
        this.bigintUnsigned255 = bigintUnsigned255;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.big_int
     *
     * @return the value of test01.big_int
     *
     * @mbggenerated
     */
    public Long getBigInt() {
        return bigInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.big_int
     *
     * @param bigInt the value for test01.big_int
     *
     * @mbggenerated
     */
    public void setBigInt(Long bigInt) {
        this.bigInt = bigInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.big_int_255
     *
     * @return the value of test01.big_int_255
     *
     * @mbggenerated
     */
    public Long getBigInt255() {
        return bigInt255;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.big_int_255
     *
     * @param bigInt255 the value for test01.big_int_255
     *
     * @mbggenerated
     */
    public void setBigInt255(Long bigInt255) {
        this.bigInt255 = bigInt255;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.varchar
     *
     * @return the value of test01.varchar
     *
     * @mbggenerated
     */
    public String getVarchar() {
        return varchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.varchar
     *
     * @param varchar the value for test01.varchar
     *
     * @mbggenerated
     */
    public void setVarchar(String varchar) {
        this.varchar = varchar == null ? null : varchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.bit
     *
     * @return the value of test01.bit
     *
     * @mbggenerated
     */
    public Boolean getBit() {
        return bit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.bit
     *
     * @param bit the value for test01.bit
     *
     * @mbggenerated
     */
    public void setBit(Boolean bit) {
        this.bit = bit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.bit_64
     *
     * @return the value of test01.bit_64
     *
     * @mbggenerated
     */
    public Boolean getBit64() {
        return bit64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.bit_64
     *
     * @param bit64 the value for test01.bit_64
     *
     * @mbggenerated
     */
    public void setBit64(Boolean bit64) {
        this.bit64 = bit64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.tiny_int
     *
     * @return the value of test01.tiny_int
     *
     * @mbggenerated
     */
    public Byte getTinyInt() {
        return tinyInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.tiny_int
     *
     * @param tinyInt the value for test01.tiny_int
     *
     * @mbggenerated
     */
    public void setTinyInt(Byte tinyInt) {
        this.tinyInt = tinyInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.tiny_int_unsigned
     *
     * @return the value of test01.tiny_int_unsigned
     *
     * @mbggenerated
     */
    public Byte getTinyIntUnsigned() {
        return tinyIntUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.tiny_int_unsigned
     *
     * @param tinyIntUnsigned the value for test01.tiny_int_unsigned
     *
     * @mbggenerated
     */
    public void setTinyIntUnsigned(Byte tinyIntUnsigned) {
        this.tinyIntUnsigned = tinyIntUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.small_int
     *
     * @return the value of test01.small_int
     *
     * @mbggenerated
     */
    public Short getSmallInt() {
        return smallInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.small_int
     *
     * @param smallInt the value for test01.small_int
     *
     * @mbggenerated
     */
    public void setSmallInt(Short smallInt) {
        this.smallInt = smallInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.small_int_unsigned
     *
     * @return the value of test01.small_int_unsigned
     *
     * @mbggenerated
     */
    public Short getSmallIntUnsigned() {
        return smallIntUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.small_int_unsigned
     *
     * @param smallIntUnsigned the value for test01.small_int_unsigned
     *
     * @mbggenerated
     */
    public void setSmallIntUnsigned(Short smallIntUnsigned) {
        this.smallIntUnsigned = smallIntUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.char_utf8
     *
     * @return the value of test01.char_utf8
     *
     * @mbggenerated
     */
    public String getCharUtf8() {
        return charUtf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.char_utf8
     *
     * @param charUtf8 the value for test01.char_utf8
     *
     * @mbggenerated
     */
    public void setCharUtf8(String charUtf8) {
        this.charUtf8 = charUtf8 == null ? null : charUtf8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.char_utf8gbk
     *
     * @return the value of test01.char_utf8gbk
     *
     * @mbggenerated
     */
    public String getCharUtf8gbk() {
        return charUtf8gbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.char_utf8gbk
     *
     * @param charUtf8gbk the value for test01.char_utf8gbk
     *
     * @mbggenerated
     */
    public void setCharUtf8gbk(String charUtf8gbk) {
        this.charUtf8gbk = charUtf8gbk == null ? null : charUtf8gbk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.date
     *
     * @return the value of test01.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.date
     *
     * @param date the value for test01.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.datetime
     *
     * @return the value of test01.datetime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.datetime
     *
     * @param datetime the value for test01.datetime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.timestamp
     *
     * @return the value of test01.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.timestamp
     *
     * @param timestamp the value for test01.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.float_type
     *
     * @return the value of test01.float_type
     *
     * @mbggenerated
     */
    public Float getFloatType() {
        return floatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.float_type
     *
     * @param floatType the value for test01.float_type
     *
     * @mbggenerated
     */
    public void setFloatType(Float floatType) {
        this.floatType = floatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.float_unsigned
     *
     * @return the value of test01.float_unsigned
     *
     * @mbggenerated
     */
    public Float getFloatUnsigned() {
        return floatUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.float_unsigned
     *
     * @param floatUnsigned the value for test01.float_unsigned
     *
     * @mbggenerated
     */
    public void setFloatUnsigned(Float floatUnsigned) {
        this.floatUnsigned = floatUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.decimal
     *
     * @return the value of test01.decimal
     *
     * @mbggenerated
     */
    public Long getDecimal() {
        return decimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.decimal
     *
     * @param decimal the value for test01.decimal
     *
     * @mbggenerated
     */
    public void setDecimal(Long decimal) {
        this.decimal = decimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.numeric
     *
     * @return the value of test01.numeric
     *
     * @mbggenerated
     */
    public Long getNumeric() {
        return numeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.numeric
     *
     * @param numeric the value for test01.numeric
     *
     * @mbggenerated
     */
    public void setNumeric(Long numeric) {
        this.numeric = numeric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.double_type
     *
     * @return the value of test01.double_type
     *
     * @mbggenerated
     */
    public Double getDoubleType() {
        return doubleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.double_type
     *
     * @param doubleType the value for test01.double_type
     *
     * @mbggenerated
     */
    public void setDoubleType(Double doubleType) {
        this.doubleType = doubleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.double_unsigned
     *
     * @return the value of test01.double_unsigned
     *
     * @mbggenerated
     */
    public Double getDoubleUnsigned() {
        return doubleUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.double_unsigned
     *
     * @param doubleUnsigned the value for test01.double_unsigned
     *
     * @mbggenerated
     */
    public void setDoubleUnsigned(Double doubleUnsigned) {
        this.doubleUnsigned = doubleUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.integer_type
     *
     * @return the value of test01.integer_type
     *
     * @mbggenerated
     */
    public Integer getIntegerType() {
        return integerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.integer_type
     *
     * @param integerType the value for test01.integer_type
     *
     * @mbggenerated
     */
    public void setIntegerType(Integer integerType) {
        this.integerType = integerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.integer_unsigned
     *
     * @return the value of test01.integer_unsigned
     *
     * @mbggenerated
     */
    public Integer getIntegerUnsigned() {
        return integerUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.integer_unsigned
     *
     * @param integerUnsigned the value for test01.integer_unsigned
     *
     * @mbggenerated
     */
    public void setIntegerUnsigned(Integer integerUnsigned) {
        this.integerUnsigned = integerUnsigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.time
     *
     * @return the value of test01.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.time
     *
     * @param time the value for test01.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.tinytext
     *
     * @return the value of test01.tinytext
     *
     * @mbggenerated
     */
    public String getTinytext() {
        return tinytext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.tinytext
     *
     * @param tinytext the value for test01.tinytext
     *
     * @mbggenerated
     */
    public void setTinytext(String tinytext) {
        this.tinytext = tinytext == null ? null : tinytext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.year
     *
     * @return the value of test01.year
     *
     * @mbggenerated
     */
    public Date getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.year
     *
     * @param year the value for test01.year
     *
     * @mbggenerated
     */
    public void setYear(Date year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.enum_type
     *
     * @return the value of test01.enum_type
     *
     * @mbggenerated
     */
    public String getEnumType() {
        return enumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.enum_type
     *
     * @param enumType the value for test01.enum_type
     *
     * @mbggenerated
     */
    public void setEnumType(String enumType) {
        this.enumType = enumType == null ? null : enumType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.binary
     *
     * @return the value of test01.binary
     *
     * @mbggenerated
     */
    public byte[] getBinary() {
        return binary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.binary
     *
     * @param binary the value for test01.binary
     *
     * @mbggenerated
     */
    public void setBinary(byte[] binary) {
        this.binary = binary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.blob
     *
     * @return the value of test01.blob
     *
     * @mbggenerated
     */
    public byte[] getBlob() {
        return blob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.blob
     *
     * @param blob the value for test01.blob
     *
     * @mbggenerated
     */
    public void setBlob(byte[] blob) {
        this.blob = blob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test01.text
     *
     * @return the value of test01.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test01.text
     *
     * @param text the value for test01.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", intUnsigned=").append(intUnsigned);
        sb.append(", intType=").append(intType);
        sb.append(", bigintUnsigned20=").append(bigintUnsigned20);
        sb.append(", bigintUnsigned255=").append(bigintUnsigned255);
        sb.append(", bigInt=").append(bigInt);
        sb.append(", bigInt255=").append(bigInt255);
        sb.append(", varchar=").append(varchar);
        sb.append(", bit=").append(bit);
        sb.append(", bit64=").append(bit64);
        sb.append(", tinyInt=").append(tinyInt);
        sb.append(", tinyIntUnsigned=").append(tinyIntUnsigned);
        sb.append(", smallInt=").append(smallInt);
        sb.append(", smallIntUnsigned=").append(smallIntUnsigned);
        sb.append(", charUtf8=").append(charUtf8);
        sb.append(", charUtf8gbk=").append(charUtf8gbk);
        sb.append(", date=").append(date);
        sb.append(", datetime=").append(datetime);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", floatType=").append(floatType);
        sb.append(", floatUnsigned=").append(floatUnsigned);
        sb.append(", decimal=").append(decimal);
        sb.append(", numeric=").append(numeric);
        sb.append(", doubleType=").append(doubleType);
        sb.append(", doubleUnsigned=").append(doubleUnsigned);
        sb.append(", integerType=").append(integerType);
        sb.append(", integerUnsigned=").append(integerUnsigned);
        sb.append(", time=").append(time);
        sb.append(", tinytext=").append(tinytext);
        sb.append(", year=").append(year);
        sb.append(", enumType=").append(enumType);
        sb.append(", binary=").append(binary);
        sb.append(", blob=").append(blob);
        sb.append(", text=").append(text);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}