package com.bj.dao;

import com.bj.entity.SysRegion;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SysRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int insert(SysRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    SysRegion selectByPrimaryKey(String regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    List<SysRegion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRegion record);


    List<SysRegion> selectByCode(@Param("regionParentId") String cityCode);
}