package com.bj.dao;

import com.bj.entity.TblUsers;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TblUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated
     */
    int insert(TblUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated
     */
    TblUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated
     */
    List<TblUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblUsers record);
}