package com.bj.dao;

import com.bj.entity.Test01;
import org.apache.ibatis.annotations.Mapper;

import java.util.Date;
import java.util.List;

@Mapper
public interface Test01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer intUnsigned);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbggenerated
     */
    int insert(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbggenerated
     */
    Test01 selectByPrimaryKey(Integer intUnsigned);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbggenerated
     */
    List<Test01> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Test01 record);

    List<Date> selectDataAttribute();

}